### ISSUE TITLE
SONGS | Position of Spotify or Youtube link button

### ISSUE THREAD

**Issue by riplive** [ripliveit/riplive.it#34]
Put the Spotify or Youtube button on top of the page.

**Comment by gabrieledarrigo** [comment]
Why? Wasn't the information to be put on top?

**Comment by riplive** [comment]
Yes but the link button are even below the textarea

**Comment by gabrieledarrigo** [comment]
Intentionally yes, why put them on top when they are only link to pages that are external to riplive.it?
I propose to leave them where they actually are, waiting for the extra functionality to be implemented, like the song / video playng.
